parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: diapason
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 1e74edfe52a1014e00b11704e95099a33734d8b6
    database_path: null
