parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: diapason_prod
    database_user: diapason_root
    database_password: 123dev
    mailer_transport: smtp
    mailer_host: mail.3ad.digin.fr
    mailer_user: contact@3ad.digin.fr
    mailer_password: 123dev
    locale: fr
    secret: 1e74edfe52a1014e00b11704e95099a33734d8b6
    database_path: null
