digin_user:
    resource: "@DiginUserBundle/Resources/config/routing.yml"
    prefix:   /

digin_home:
    resource: "@DiginHomeBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
