digin_home_homepage:
    pattern:  /
    defaults: { _controller: DiginHomeBundle:Default:index }

digin_home_diapason:   
    pattern:  /diapason
    defaults: { _controller: DiginHomeBundle:Default:diapason}

digin_home_contact:    
    pattern:  /contact
    defaults: { _controller: DiginHomeBundle:Default:contact }
