parameters:
#    digin_user.example.class: Digin\UserBundle\Example

services:
#    digin_user.example:
#        class: %digin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
