parameters:
#    digin_user.example.class: Digin\UserBundle\Example

services:
#    digin_user.example:
#        class: %digin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
   digin_user_registration:
      class: Digin\UserBundle\Form\UserType
      tags:
         -  { name: form.type }